CLASS zbp_ll_r_mitarbeiter DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZLL_R_Mitarbeiter.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_LL_R_MITARBEITER IMPLEMENTATION.
ENDCLASS.
